- name: Setup and Update Raspberry Pi for Bootable Serial Monitoer
  hosts: raspberry_pi_3B+
  become: 'yes'
  vars:
    motd_content: |
      ____ _____ _____ _____ _____ __       _____ _____ _____ 
      |   __|   __| __  |     |  _  |  |     |     |     |   | |
      |__   |   __|    -|-   -|     |  |__   | | | |  |  | | | |
      |_____|_____|__|__|_____|__|__|_____|  |_|_|_|_____|_|___|
                                                          
       Welcome to Serial Monitor
       Saurabh Datta
       2024                                             

  tasks:
    - name: Update apt cache (equivalent to apt-get update -y)
      apt:
        update_cache: 'yes'
        force_apt_get: 'yes'
    
    - name: Hide Raspberry Pi logo during boot and disable logo on top left corner
      lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: '^(.*)$'
        line: '\1 logo.nologo console_logo.enabled=0'
        backrefs: yes
        
    - name: Set custom MOTD
      copy:
        content: "{{ motd_content }}"
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'

    - name: Install required packages
      apt:
        name:
          - git
          - tmux
          - neofetch
          - vim
          - vlc
        state: present
        force_apt_get: 'yes'

    - name: Display installation complete message
      debug:
        msg: >-
          System Configuration and Installation complete! 